language: node_js
node_js:
- '8'
notifications:
  slack:
    secure: GyVSookqiHzp++7jpInMJqE0FyAki09364rOX1Er+JGo5TRl/h+S3hPqtumFnncwSWDcgPVNAc85hyDwLzvDtsq4riSaxvPHipQSv7ozTniJYaUlbyYsBNKF1OodFeqtNgT2bGiVMBWBy5cq2LFS2X9DuRhJTAPa3tKG0da6PMZx7O6PQyMB+5dbhKP4b0qpNmJURQMQtVeZqZy5gumxDeL9DZfCOQCi9aTu40OQmDfj/XJx+UuH8EWLV2J08xwIgqdx/oiKR1+iNyKCCeC2jRinJO88SDO0zhU4jUYiUuZ0TlDU4xrH/S3sumfX+fDu1dAOXf+00pI4oUcsh60T55uNYtoVrJUFUx3aL5Nu8kVJqiwZdJ738IPgaZmLGJjuVgsfF+gzvsSqW21whGM3s6i5hYg8dJkQgw/31dzMkY/tXhz1zo0VbTN3lAHb9ym+HO9k6a7NAOwXgVXwhyip00NbbJ47chGWLmf19rv7K2uaqp0Wd1koYJrMsY0TtOMG+NtJBkHCLnqMJPTt5PSacKd9fT8H+4uL5I7RYbJ1zmB2S2mlso/l9BPM8wU6UwNDBmFkUpvQIv2LprGjFBEuSVtLzPUEyoJtwVTazCA1XhFXaG9BkZy8ThR3wqo7/WUo793GLhtgNqMFBOrKfL13W77IIXu+jN3NC1LJPGgGddY=
